name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.10.11'
          cache: 'pip'  # Enable caching for faster runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install test requirements

      - name: Verify test directory exists
        id: check-tests
        run: |
          if [ -d "tests" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Test directory found"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "::warning::No tests directory found"
          fi

      - name: Run unit tests with coverage
        if: steps.check-tests.outputs.exists == 'true'
        run: |
          python -m pytest tests/ \
            --cov=./ \
            --cov-report=xml \
            --junitxml=test-results.xml \
            -v
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload coverage report
        if: steps.check-tests.outputs.exists == 'true'
        uses: codecov/codecov-action@v3

      - name: Upload test results
        if: steps.check-tests.outputs.exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results.xml
            coverage.xml

      - name: Handle missing tests
        if: steps.check-tests.outputs.exists == 'false'
        run: |
          echo "::warning::No tests were executed"
          exit 0  # Change to exit 1 if you want missing tests to fail